// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-2Am69hIxOMr8UIiudpY7vGxEniw0iBE',
    appId: '1:920334294602:android:4c83ad9fe2f9a5be9b10b3',
    messagingSenderId: '920334294602',
    projectId: 'my-fruitveggie',
    storageBucket: 'my-fruitveggie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf-vWy8uhSZMUQZ9LM6Nh2Znf1-BM-YQY',
    appId: '1:920334294602:ios:86d04f4542dfa28d9b10b3',
    messagingSenderId: '920334294602',
    projectId: 'my-fruitveggie',
    storageBucket: 'my-fruitveggie.firebasestorage.app',
    iosBundleId: 'com.example.harvestapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf-vWy8uhSZMUQZ9LM6Nh2Znf1-BM-YQY',
    appId: '1:920334294602:ios:86d04f4542dfa28d9b10b3',
    messagingSenderId: '920334294602',
    projectId: 'my-fruitveggie',
    storageBucket: 'my-fruitveggie.firebasestorage.app',
    iosBundleId: 'com.example.harvestapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-2Am69hIxOMr8UIiudpY7vGxEniw0iBE',
    appId: '1:920334294602:web:4c83ad9fe2f9a5be9b10b3',
    messagingSenderId: '920334294602',
    projectId: 'my-fruitveggie',
    storageBucket: 'my-fruitveggie.firebasestorage.app',
    authDomain: 'my-fruitveggie.firebaseapp.com',
  );
}
